EventApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('auth/', include('user_auth.urls', namespace='user_auth')),
    path('book/', include('booking.urls', namespace='booking'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
    path('', views.my_events, name='my_events'),
    path('delete_book/<int:event_id>', views.delete_book, name='delete_book')
]

main/urls.py
from django.urls import path
from . import views
from booking import views as booking_views


app_name = 'main'

urlpatterns = [
    path('', views.main_events, name='main'),
    path('event/<int:event_id>', views.event_description, name='event_description'),
    path('event/<int:event_id>/take_part', booking_views.take_part, name='take_part'),
    path('create_event/', views.create_event, name='create_event')
]

user_auth/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from EventApp import settings

app_name = 'user_auth'

urlpatterns = [
    path('login', views.user_login, name='user_login'),
    path('register/', views.register, name='register'),
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='user_logout',)
]

booking/models.py
from django.db import models
from main.models import Event
from django.contrib.auth.models import User


class EventUser(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return [self.event, self.user]

main/models.py
from django.db import models
import datetime


class CategoryEvent(models.Model):
    title = models.CharField(verbose_name="Тип мероприятия", max_length=255)

    def __str__(self):
        return self.title


class Event(models.Model):
    title = models.CharField(verbose_name="Название мероприятия", max_length=255)
    organizer = models.CharField(verbose_name="Организаторы", max_length=255, default="Организация")
    description = models.TextField(verbose_name="Описание мероприятия")
    event_time = models.TimeField(default=datetime.time(12, 0))
    event_date = models.DateField(default=datetime.date.today)
    duration = models.FloatField(verbose_name="Продолжительность(в часах)")
    city = models.CharField(verbose_name="Город", max_length=255)
    location = models.CharField(verbose_name="Место проведения", max_length=255)
    seats_amount = models.IntegerField(verbose_name="Количество мест")
    event_type = models.ForeignKey(CategoryEvent, on_delete=models.PROTECT)
    available_seats = models.IntegerField(verbose_name="Доступное количество мест")
    photo = models.ImageField(upload_to='uploads/', default='uploads/default.png')

    def save(self, *args, **kwargs):
        # Calculate and set the initial value of available_seats

        super(Event, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

user_auth/models.py
from django.db import models

# Create your models here.

main/forms.py
from .models import Event
from django import forms


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ["title", "organizer", "description", "event_time", "event_date", "duration", "city", "location",
                  "seats_amount", "event_type", "available_seats", "photo"]

user_auth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError



class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(label='username', min_length=5, max_length=150)
    email = forms.EmailField(label='email')
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def username_clean(self):
        username = self.cleaned_data['username'].lower()
        new = User.objects.filter(username=username)
        if new.count():
            raise ValidationError("User Already Exist")
        return username

    def email_clean(self):
        email = self.cleaned_data['email'].lower()
        new = User.objects.filter(email=email)
        if new.count():
            raise ValidationError(" Email Already Exist")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")
        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user

booking/views.py
from django.shortcuts import render
from .models import EventUser
from main.models import Event
from django.core.exceptions import ObjectDoesNotExist


def take_part(request, event_id):
    event = Event.objects.get(id=event_id)
    event.available_seats -= 1
    event.save()

    event_user = EventUser(event=event, user=request.user)
    event_user.save()

    my_events_list = EventUser.objects.filter(user=request.user)

    return render(request, 'booking/my_events.html', {'my_events_list': my_events_list, 'new_event': event})


def my_events(request):
    my_events = EventUser.objects.filter(user=request.user)
    return render(request, 'booking/my_events.html', {'my_events_list': my_events, 'new_event': None})


def delete_book(request, event_id):
    event = Event.objects.get(id=event_id)
    event_user = EventUser.objects.get(event=event, user=request.user)
    event_user.delete()
    event.available_seats += 1
    event.save()

    return render(request, 'booking/my_events.html', {'my_events_list': my_events, 'new_event': None,
                                                      'deleted_event': event})

main/views.py
from django.shortcuts import render
from .models import *
from booking.models import *
from .forms import EventForm
from django.shortcuts import redirect


def main_events(request):
    events = Event.objects.all()
    return render(request, 'main/main.html', {'events': events})


def event_description(request, event_id):
    event = Event.objects.get(id=event_id)
    already_take_part = False
    if request.user.is_authenticated:
        if event in [i.event for i in EventUser.objects.filter(user=request.user)]:
            already_take_part = True
    return render(request, 'main/description.html', {'event': event, 'already_take_part': already_take_part})


def create_event(request):
    if request.method == "POST":
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            events = Event.objects.all()
            return render(request, 'main/main.html', {'events': events})

    form = EventForm()
    return render(request, 'main/event_creator.html', {'form': form})

user_auth/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from main.models import *
# Create your views here.
def register(request):
    if request.method == 'POST':
        register_form = CustomUserCreationForm(request.POST)
        if register_form.is_valid():
            user = register_form.save()
            login(request, user)
            return redirect('/')
    register_form = CustomUserCreationForm
    return render(request, 'user_auth/register.html', context={'register_form': register_form})


def user_login(request):
    if request.method == 'POST':
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')

    login_form = AuthenticationForm()
    return render(request=request, template_name='user_auth/login.html', context={'login_form': login_form})


def user_logout(request):
    logout(request)

booking/templates/booking/my_events.html
{% extends 'main/main.html'%}
{% load static %}
{%block content%}

<div class="col-md-4" style="margin-top: 5%; margin-left: 10%;">
    {% if new_event is not None %}
      <h3>Вы успешно добавлены на мероприятие "{{new_event.title}}"</h3>
    {% endif %}
    {% if deleted_event is not None %}
        <h3>Вы успешно покинули мероприятие {{deleted_event.title}}</h3>
    {% endif %}
    <h2>Мои мероприятия</h2>
      <div class="position-sticky" style="top: 2rem;">
        <div>
          <ul class="list-unstyled">
            {% for my_event in my_events_list %}

              <li><a href="{% url 'main:event_description' my_event.event.id%}">{{my_event.event.title}}</a></li>
              <li>Время: {{my_event.event.event_time}}, {{my_event.event.event_date}}</li>
              <li>Место проведения: {{my_event.event.city}}, {{my_event.event.location}}</li>
              <li><a href="{% url 'booking:delete_book' my_event.event.id%}">Отменить бронирование</a></li>

            {% endfor %}
          </ul>
        </div>


      </div>
    </div>
{%endblock%}

main/templates/main/description.html
{% extends 'main/main.html'%}
{% load static %}
{% block content %}

<div class="row g-5" style="margin-left: 5%; margin-top: 1%" xmlns="http://www.w3.org/1999/html">
    <div class="col-md-8">

      <article class="blog-post">
        <h1><strong>{{event.title}}</strong></h1>
        <img src="{{event.photo.url}}" width="1000px" style="margin-top:2%;">

        <hr>
        <h2>Описание</h2>
        <p style="font-size: 20px;">{{event.description}}</p>
        <br>
        <h3>Количество доступных мест: {{event.available_seats}}</h3>
        {% if user.is_authenticated%}
          {% if already_take_part%}
            <h4>Вы уже участвуете в данном мероприятии, <a href="{% url 'booking:my_events' %}">Управлять моими мероприятиями</a></h4>
          {% else %}
            <h4><a href="{% url 'main:take_part' event.id %}">Зарегистрироваться на мероприятие</a></h4>
          {% endif %}
        {% else %}
          <h4>Для участия на мероприятие <a href="{% url 'user_auth:user_login'%}">Войдите</a>
            или <a href="{% url 'user_auth:register'%}">Зарегистрируйтесь</a></h4>
        {% endif %}
      </article>

    </div>

    <div class="col-md-4">
      <div class="position-sticky" style="top: 2rem;">
        <div>
          <h2 class="fst-italic">Информация о событии</h2>
          <ul class="list-unstyled">
            <li>
              <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="#">
                <div class="col-lg-8">
                  <h4 class="mb-0">Время: {{event.event_time}}</h4>
                </div>
              </a>
            </li>
            <li>
              <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="#">
                <div class="col-lg-8">
                  <h4 class="mb-0">Дата: {{event.event_date}}</h4>
                </div>
              </a>
            </li>
            <li>
              <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="#">
                <div class="col-lg-8">
                  <h4 class="mb-0">Город: {{event.city}}</h4>
                </div>
              </a>
            </li>
            <li>
              <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="#">
                <div class="col-lg-8">
                  <h4 class="mb-0">Место проведение: {{event.location}}</h4>
                </div>
              </a>
            </li>
            <li>
              <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="#">
                <div class="col-lg-8">
                  <h4 class="mb-0">Длительность: {{event.duration}} часа</h4>
                </div>
              </a>
            </li>
            <li>
              <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="#">
                <div class="col-lg-8">
                  <h4 class="mb-0">Количество доступных мест: {{event.available_seats}}</h4>
                </div>
              </a>
            </li>
            <li>
              <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="#">
                <div class="col-lg-8">
                  <h4 class="mb-0">Организаторы: {{event.organizer}}</h4>
                </div>
              </a>
            </li>
            <li>
              <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="#">
                <div class="col-lg-8">
                  <h4 class="mb-0">Тип мероприятия: {{event.event_type}}</h4>
                </div>
              </a>
            </li>
          </ul>
        </div>


      </div>
    </div>
  </div>
  {% endblock %}

main/templates/main/event_creator.html
{% extends 'main/main.html'%}
{% load static %}
{% block content %}

<div style="margin-top:3%; margin-left:30%;">
    <form method="post">
        <h1>Cоздание мероприятия</h1>
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Создать мероприятие</button>
    </form>
</div>

{% endblock %}

main/templates/main/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Events</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"></path>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (dark)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="dark" aria-pressed="true">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="auto" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>


<header data-bs-theme="dark">
  <div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4>About</h4>
          <p class="text-body-secondary">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4>Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'main:main' %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>Events</strong>
      </a>
      {% if user.is_authenticated %}
      <a href="#" class="navbar-brand d-flex align-items-center">
        <strong>{{user.username}}</strong>
      </a>
       <a href="{% url 'booking:my_events' %}" class="navbar-brand d-flex align-items-center">
        <strong>Мои мероприятия</strong>
      </a>
      <a href="{% url 'user_auth:user_logout'%}" class="navbar-brand d-flex align-items-center">
        <strong>Выйти</strong>
      </a>
          {% if user.username == 'admin'%}
        <a href="{% url 'main:create_event' %}" class="navbar-brand d-flex align-items-center">
        <strong>УПРАВЛЯТЬ МЕРОПРИЯТИЯМИ(admin only)</strong>
      </a>
        {% endif %}
      {% else %}
      <a href="{% url 'user_auth:user_login'%}" class="navbar-brand d-flex align-items-center">
        <strong>Войти</strong>
      </a>
      <a href="{% url 'user_auth:register'%}" class="navbar-brand d-flex align-items-center">
        <strong>Зарегистрироваться</strong>
      </a>
      {% endif %}
    </div>
  </div>
</header>

    {% block content %}
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Список мероприятии</h1>
        <p class="lead text-body-secondary">Этот веб-сайт создан для отображения всех предстоящих мероприятий, организуемых нашей командой. Здесь вы можете узнать о последних событиях, и быть в курсе всех новостей и обновлений. Мы постарались сделать информацию доступной и удобной для вас.</p>
      </div>
    </div>
  </section>


<h1 class="fw-light" align="center"><strong>БЛИЖАЙШИЕ КРУПНЫЕ СОБЫТИЯ</strong></h1>
  <div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for event in events %}
        <div class="col"><a href="{% url 'main:event_description' event.id %}" style="text-decoration: none;">
          <div class="card shadow-sm">
              <img src="{{event.photo.url}}" width="100%" height="300px">
            <div class="card-body">
              <p class="card-text">{{event.title}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Book</button>
                </div>
                <small class="text-body-secondary">Длительность: {{event.duration}} часа</small>
                <small class="text-body-secondary">Свободные места: {{event.available_seats}}</small>
              </div>
            </div>
          </div>
          </a>
        </div>
          {% endfor %}
      </div>
    </div>
  </div>

</main>
{% endblock %}
<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is © Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>
<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

user_auth/templates/user_auth/login.html
{% extends 'main/main.html' %}
{% load static %}


{% block content%}
    <form method="POST" style="margin-top:5%; margin-left:30%; font-size: 20px;">
        <h1>Войти</h1>
        {% csrf_token %}
        {{login_form.as_p}}
        <input type="submit" value="Войти">
    </form>
{% endblock %}

user_auth/templates/user_auth/register.html
{% extends 'main/main.html' %}
{% load static %}

{% block content%}
    <div style="margin-top:5%; margin-left:30%; font-size: 20px;">
        <p style="font-size: 50px;">Регистрация</p>
        <form method="post">
             {% csrf_token %}
             <table>
                {{ register_form }}
                 <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Register" /></td>
                </tr>
             </table>
         </form>
    </div>
{%endblock%}